# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 313)
        MainWindow.setStyleSheet("QWidget#centralwidget {background-image: url(:/src/background.jpg);}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("font: 87 italic 19pt \"Segoe UI Black\";")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.message_text.setStyleSheet("background-color: rgba(56, 56, 56, 0);\n"
"color: rgb(255, 255, 255);")
        self.message_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.message_text.setWordWrap(True)
        self.message_text.setObjectName("message_text")
        self.verticalLayout.addWidget(self.message_text)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_text.setText(_translate("MainWindow", "ПОДОЖДИТЕ..."))
